name: Auto-Approve and Auto-Merge PRs

on:
  workflow_call:
  check_suite:
    types:
      - completed

jobs:
  auto-approve-merge-dependabot:
    uses: Neovici/cfg/.github/workflows/automerge.yml@master
    secrets: inherit
