---
name: Github CI
on:
  push:
    branches:
      - master
jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install
      run: npm ci

    - name: Deploy storybook
      run: npm run storybook:deploy -- --ci
      env:
         GH_TOKEN: Neovici:${{ secrets.GITHUB_TOKEN }}
